### ISSUE TITLE
Write something about executing trusted applications somewhere.

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#14]
Eg. what language are they written in, how are they developed? what special precautions are taken to ensure code running as expected?

**Comment by ikdekker** [comment]
This has not been written about in the draft. I'd like someone elses opinion on this. Should we write about this?

Trusted applications (TA) are a pretty important aspect of TEE and we write about them in chapter IV. Is it necessary to explain them? How deep to we want to go into them, since there are some academic TEEs, which have been designed to write TAs. The development of these TAs happen in C most of the time. Andix OS, for example allows development in .NET (using mono). That part does not seem as important for our research. Still, porting ARM TrustZone to linux with mono is the main objective of Andix OS, what else will we say about each OS? A very superficial explanation of what it runs on?

This is from [this paper](https://arxiv.org/pdf/1506.07367.pdf), a pretty simple definition. We could add something similar.

```
Trusted Application (TA): An application encapsulating the
security-critical functionality to be run within the TEE. This
may be a service style application that provides a general
feature, such as a generic cryptographic keystore, or it could
be designed to offload a very specific part of an application
that is running in the REE, such as a portion of the client state
machine in a security protocol like TLS.
```

**Comment by ikdekker** [comment]
Anyone?

**Comment by soostmeijer** [comment]
I think this could certainly add something to the paper, and it is always good to add the definition  of certain key words.

**Comment by ikdekker** [comment]
I will pick this up. Expected to be done at 5pm today
