### ISSUE TITLE
Decide on citation style

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#2]
We should agree on a single style of reference. [Here's](http://www.citethisforme.com/guides) a guide.

Citation Styles:

- APA. APA is an author/date based style. This means emphasis is placed on the author and the date of a piece of work to uniquely identify it.
- MLA. MLA is most often applied by the arts and humanities, particularly in the USA. It is arguably the most well used of all of the citation styles.
- Harvard. Harvard is very similar to APA. Where APA is primarily used in the USA, Harvard referencing is the most well used referencing style in the UK and Australia, and is encouraged for use with the humanities.
- Vancouver. The Vancouver system is mainly used in medical and scientific papers.
- Chicago and Turabian. These are two separate styles but are very similar, just like Harvard and APA. These are widely used for history and economics.

**Comment by ikdekker** [comment]
My preference is APA, MLA is fine too.

**Comment by ArnoutvdKnaap** [comment]
APA is fine with me

**Comment by devos50** [comment]
For your paper, please use the two-column IEEE template + IEEE citation style: https://en.wikipedia.org/wiki/IEEE_style

**Comment by joasiee** [comment]
Updated the overleaf tex file to match this template

**Comment by ikdekker** [comment]
For easy access:  
[guide to IEEE citation](http://libraryguides.vu.edu.au/ieeereferencing/gettingstarted)
