### ISSUE TITLE
How to document literature research

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#3]
Currently, we have a [file](https://github.com/ikdekker/bsc-smart-contract-research/blob/master/docs/paper_collection.md) where papers are stored, we might need to use a method to index them, with proper categories.

A paper with some good research examples can be found on [BrightSpace, the seminar course](https://brightspace.tudelft.nl/d2l/le/content/127816/viewContent/1043619/View). See chapter II Method.

I don't know if I can post the document here so I didn't.

**Comment by ikdekker** [comment]
Possible matrix for indexing(needs improvement, mostly an example): 

|paper|category|insights|source?
|-----|--------|--------|---|
|Casper FFG<sup>1</sup>|partial consensus mechanism|This paper helped me gain an understanding of Ethereums new protocols and shows that more computations per second are achievable.|..|
|Second paper<sup>2</sup>|smart contracts in some area|The ideas presented in this paper show that...|..|


1: Buterin.. Casper the Friendly Finality Gadget....2019 [in Citation standard format]

**Comment by joasiee** [comment]
Maybe just a category with a table like yours beneath?

Ex:

### partial consensus mechanism

| paper | insights | source | notes |
| :---|:---|---|---|
| Casper FFG | This paper helped me gain an understanding of Ethereums new protocols and shows that more computations per second are achievable | |

Where notes would link to a separate file containing extra notes if necessary?

**Comment by ikdekker** [comment]
We should see if it is possible to create a paper search flow diagram

From some student paper:

![ss+(2019-03-20+at+12 39 03)](https://user-images.githubusercontent.com/9272424/54681642-2b9edb80-4b0d-11e9-95b3-95d7b0cc90a4.png)

**Comment by ikdekker** [comment]
This kind of changed and does not seem very relevant anymore.
