### ISSUE TITLE
Write ~2 pages

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#5]
Just an issue to keep track of the progress on the paper.

**Comment by ikdekker** [comment]
Please make sure your work includes multiple references to _credible_ sources.

**Comment by ikdekker** [comment]
@devos50 

Do you have an opinion about what our research direction or definition of TEE should consist of? It could be argued that trusted code execution is defined as either:

 - **confidential** execution of code (where the executing party is unaware of the data)
 - **integrity** of code execution (where the result of a computation is consistent/always the same)

or would both be interesting to look at?

**Comment by devos50** [comment]
@ikdekker I would say that both are interesting.

**Comment by ikdekker** [comment]
@devos50 if we send in a draft tomorrow for review, would it make a difference whether we send it before a certain deadline (eg 12:00 / 15:00). Which may result in faster feedback (on the same day?).

**Comment by devos50** [comment]
@ikdekker I aim to immediately review it when receiving it during working hours. If you send it tomorrow, I will try to give feedback the same day.

**Comment by ikdekker** [comment]
@soostmeijer 
[Paper met decentralized systems definitie](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/stamp/stamp.jsp?tp=&arnumber=6312966)
