### ISSUE TITLE
Write partial sections of our assigned tasks

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#6]
Currently our work is assigned as follows:

 - [x] @ArnoutvdKnaap will write general info - intro, what are the goals and the contributions of this project
 - [x] @justino10950 will write about the concept of code security, first without blockchain, later including BC
 - [x] @soostmeijer will write about the definition of a decentralized environment
 - [x] @ikdekker will write about which types and which environments are currently used for TEE
 - [x] @joasiee  will write about trust, how do we define & enforce it? (concerning code execution)

**Comment by ikdekker** [comment]
These descriptions were deducted from the research question:

(survey) how can we trustfully execute code in a decentralized environment?

sub-question and subjects to write about:
[Justin/Joas] What is security? not blockchain specific.
[Sander] What is a decentralized environment? (introduction)
[Nick] What environments exist?
[Justin/Joas] How do we define trust + how can we enforce trust?

**Comment by ikdekker** [comment]
@joasiee Please update your research in the Overleaf file.

**Comment by ikdekker** [comment]
If possible, try to update the concept map according to your findings.

**Comment by joasiee** [comment]
Yes will do so tonight!
