### ISSUE TITLE
Update paper title

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#8]
The paper is still named survey: smart contracts.

If anyone has a good suggestion for a title please post it here. 

We should probably derive it from our research question (it might even be the "same"):  
(survey) how can we trustfully execute code in a decentralized environment?

Ofcourse the title, like our research question is subject to change.

**Comment by ikdekker** [comment]
The research question was changed today, it has become:

How can we execute code in a secure and trusted manner?

However, this question is answered by a survey, so does the title become:

A survey: How can we execute code in a secure and trusted manner?

**Comment by ArnoutvdKnaap** [comment]
Maybe we should do it the other way around, like: Executing code in a secure and trusted manner: a Survey

**Comment by devos50** [comment]
Suggestion: "An exploration of Trustful, Secure Code Execution and its Applications"
